### ISSUE TITLE
wiki: getting all bulk purchase shops example needs ~

### ISSUE THREAD

**Issue by goldfndr** [vivreanantes/cartovrac#13]
The wiki page for downloading has an example for getting all bulk purchase shops, but it uses the `=` operator for the tags. Overpass requires use of the `~` operator to match a regular expression. Changing the URL from `=` to `~` (two instances) changes the results from none to many.

**Comment by AntoineJaury** [comment]
Indeed, there was a typo in the URL. I've corrected the wiki. Thanks for the feedback :)
